export enum ApiEndPoint {
  login = 'Account/Login',
  register = 'Account/Register',
  confirmEmail = 'Account/ConfirmEmail',
  resendOtp = 'Account/ResendEmail',
  forgotPassword = 'Account/ForgotPassword',
  resetPassword = 'Account/ResetPassword',
  changePassword = 'Account/ChangePassword',
  linkedUsers = 'User/LinkedUsers',
  invoiceList = 'Invoice/InvoiceList',
  getInvoiceById = "Invoice/GetInvoice",
  deleteInvoice = "Invoice/DeleteInvoice",
  itemList = 'Management/ItemList',
  customersList = 'Management/CustomerList',
  addNewItem = 'Management/CreateItem',
  getItemById = 'Management/GetItem',
  deleteItem = 'Management/DeleteItem',
  addNewCustomer = 'Management/CreateCustomer',
  getCustomerById = "Management/GetCustomer",
  deleteCustomer = 'Management/DeleteCustomer',
}
